name: CI

on: [pull_request, push]

jobs:
  prepare:
    name: Prepare
    runs-on: ubuntu-latest
    steps:
      - uses: DerYeger/pnpm-setup-action@master
        with:
          node-version: 'latest'
  lint:
    name: Lint
    runs-on: ubuntu-latest
    needs: prepare
    steps:
      - uses: DerYeger/pnpm-setup-action@master
        with:
          node-version: 'latest'
      - run: pnpm lint